version: '3.8'

services:
  app:
    build: .
    container_name: churn-prediction-pipeline
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
    environment:
      - MODEL_PATH=/app/models
      - DATA_PATH=/app/data
    command: python main.py
    networks:
      - churn-network
    
  api:
    build: .
    container_name: churn-prediction-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./configs:/app/configs
    depends_on:
      - app
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000
    networks:
      - churn-network
    
  monitoring:
    build: .
    container_name: churn-prediction-monitoring
    depends_on:
      - app
      - api
    command: python src/pipeline/retraining.py --schedule weekly
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    networks:
      - churn-network

networks:
  churn-network:
    driver: bridge 