name: Run ML Pipeline and Update Dashboard

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create directories
      run: |
        mkdir -p reports/metrics
        mkdir -p reports/figures
        mkdir -p data/interim
        
    - name: Download dataset
      run: |
        # Option 1: Download from public URL
        # wget -O data/raw/churn_data.csv ${{ secrets.DATA_URL }}
        
        # Option 2: Use a small sample dataset stored in the repo
        echo "Using sample dataset for pipeline execution"
        
    - name: Run ML pipeline
      run: |
        python main.py
      env:
        GITHUB_ACTIONS: 'true'
        
    - name: List generated files
      run: |
        echo "Generated metrics files:"
        ls -la reports/metrics/
        echo "Generated visualization files:"
        ls -la reports/figures/
        
    - name: Create pipeline status file
      run: |
        echo "{\"status\":\"completed\",\"timestamp\":\"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}" > reports/pipeline_status.json
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add reports/metrics/*.json reports/pipeline_status.json
        git add reports/metrics/*.csv || true
        git add reports/figures/*.png || true
        git commit -m "Update metrics and visualizations [skip ci]" || echo "No changes to commit"
        git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
        git push 